# version: "3.7"
# services:
#   es01:
#     image: "docker.elastic.co/elasticsearch/elasticsearch:8.6.2"
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     environment:
#       node.name: es01
#       discovery.seed_hosts: es01
#       cluster.initial_master_nodes: es01
#       cluster.name: mycluster
#       bootstrap.memory_lock: "true"
#       ES_JAVA_OPTS: -Xms256m -Xmx256m
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     healthcheck:
#       test: ["CMD-SHELL", "curl https://localhost:9200"]
#       interval: 10s
#       timeout: 10s
#       retries: 120
#     volumes:
#         - C:\Users\Yan\Desktop\BDES\Dashboard\elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#   redis:
#     image: 'redis'
#     environment:
#       - ALLOW_EMPTY_PASSWORD=yes
version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    ports:
      - '9200:9200'
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - discovery.type=single-node
      
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:8.6.2
    ports:
      - '5601:5601'
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes